# Generated by Django 2.2.5 on 2019-09-20 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStorage',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserStorageEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('path', models.CharField(max_length=200)),
                ('storage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserStorage')),
            ],
        ),
    ]
