# Generated by Django 2.2.5 on 2019-10-06 11:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStorage',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('bucket_name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserStorageEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('path', models.CharField(max_length=200)),
                ('uploaded', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('details', models.CharField(blank=True, max_length=200, null=True)),
                ('userstorage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserStorage')),
            ],
        ),
    ]
