# Generated by Django 2.2.5 on 2019-09-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstorageentries',
            old_name='storage_id',
            new_name='storage',
        ),
    ]
