# Generated by Django 2.2.5 on 2019-09-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190920_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstorage',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
