# Generated by Django 2.2.5 on 2019-10-23 17:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191022_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstorageentries',
            old_name='userstorage',
            new_name='user_storage',
        ),
        migrations.AlterField(
            model_name='userstorageentries',
            name='details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userstorageentries',
            name='path',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='userstorageentries',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='UserStorageAnalyzedEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('path', models.CharField(max_length=300)),
                ('label', models.CharField(max_length=300)),
                ('user_storage_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserStorageEntries')),
            ],
        ),
    ]
