# Generated by Django 2.2.5 on 2019-09-20 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190920_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstorage',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
