# Generated by Django 2.2.5 on 2019-10-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191023_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstorageanalyzedentries',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
