# Generated by Django 2.2.6 on 2019-10-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userstorageanalyzedentries_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstorageanalyzedentries',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userstorageanalyzedentries',
            name='path',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userstorageentries',
            name='details',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userstorageentries',
            name='path',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userstorageentries',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
