# Generated by Django 2.2.5 on 2019-09-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190920_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstorage',
            name='bucket_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
