# Generated by Django 2.2.5 on 2019-09-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userstorage_bucket_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstorageentries',
            name='details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userstorageentries',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
